spring.application.name=SpringCourseSection4
logging.level.org.springframework=trace
currency-service.url= https://dev.default.test.com
currency-service.username=defaultuser.dev
currency-service.key=defaultkey.dev