spring.application.name=SpringCourseSection4
logging.level.org.springframework=debug
spring.profiles.active=dev
currency-service.url= https://default.test.com
currency-service.username=defaultuser
currency-service.key=defaultkey
