spring.application.name=SpringCourseSection4
logging.level.org.springframework=debug
spring.profiles.active=dev

currency-service.url= https://default.test.com
currency-service.username=defaultuser
currency-service.key=defaultkey

# This enables all actuator checks (like show all beans)
# management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.include = health, metrics
